import type { Metadata } from "next";
import { Karla } from "next/font/google"
import "./globals.css";
import Header from "@/components/layout/Header";
import Providers from "./providers";
import Footer from "@/components/layout/Footer";

const sans = Karla({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.className} antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
